### PR TITLE
Add object hashing callback and ws_object_hash() function

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR adds the possibility to hash an object.

It also provides a _very_ basic "hashing" function for the object type itself.

### CODE REVIEW

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
@neithernut Please review again.

**Comment by neithernut** [comment]
Do we allow objects without a valid type information?

**Comment by matthiasbeyer** [comment]
No, I wouldn't. With this patch included, we could safe ourselves a lot of headaches!

**Comment by neithernut** [comment]
Then ACK.

**Comment by matthiasbeyer** [comment]
Rebased. Feel free to merge now.

**Pull request merged**
