### PR TITLE
Cleanup ws_string type implementation

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR is a cleanup for the ws_string type implementation,
it removes whitespace, simplifies some algorithms and does
one major change: The return type of
ws_string_set_from_raw(). It adapts the calls to
this function, though.

This was pair-programmed with @manuelmessner.

### CODE REVIEW

**Comment by manuelmessner** [comment]
ACK

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
@neithernut can you please suggest commits to squash? @manuelmessner and me think it's okay the way the history looks...

**Comment by neithernut** [comment]
Well, https://github.com/matthiasbeyer/waysome/commit/a18387355a89f2ae8ff6a6dcf711856d0195a639 through https://github.com/matthiasbeyer/waysome/commit/42bbb3fe48e2d2d7b2d5373f1a6381fe09372c83 _look_ like they might be squashable.

**Comment by matthiasbeyer** [comment]
You meant the latter could be merged into the first, but the commits between differ really much semantically...

**Comment by neithernut** [comment]
I realized that. But still, would be nice if those two commits are merged.

**Comment by matthiasbeyer** [comment]
I did it already...

**Comment by neithernut** [comment]
k. ACK.

**Pull request merged**
