### PR TITLE
Move ws monitor buffer to ws buffer

### PR DESCRIPTION
**Pull request by TheNeikos**
This moves the buffer field of the `ws_monitor` struct into a `ws_image_buffer`.

### CODE REVIEW

**Comment by TheNeikos** [comment]
Once https://github.com/waysome/waysome/pull/138 is merged, I will rebase. Only the latest two commits are relevant.

**Comment by matthiasbeyer** [comment]
Can you add a bit more message to the last commit?

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
ACK.

**Pull request merged**
