### PR TITLE
Adds a memset for the ws_value_named on the stack in action/manager

### PR DESCRIPTION
**Pull request by TheNeikos**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
ACK.

Wall of shame?

**Comment by TheNeikos** [comment]
Haha

**Comment by neithernut** [comment]
Did this trigger a bug?
When I wrote this, I think I assumed that the initialization function sets all the values to a sane value. Maybe we should discuss this semantic at some point, but not in this PR.
Anyways, ACK for now.

**Comment by TheNeikos** [comment]
They usually do, but in this case it depended on an input variable.

**Pull request merged**
