### PR TITLE
Add missing callbacks for connector

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #648.

Please review.

### CODE REVIEW

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
Look at the commits. There is no squashing needed here! :smile:

**Comment by neithernut** [comment]
There _were_ fixups.
Anyways: ACK.

**Comment by matthiasbeyer** [comment]
Ups, I'm sorry. :smile:

**Pull request merged**
