### PR TITLE
Add gitignore file

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR adds a gitignore file for C sources.

It is based on the official gitignore file from github for C projects, including some other entries for (for example) youcompleteme (a vim plugin).

### CODE REVIEW

**Comment by neithernut** [comment]
ACK shamless rip from libreset.

**Comment by manuelmessner** [comment]
Please add a line containing the name .todo

**Comment by matthiasbeyer** [comment]
@manuelmessner why do you want that?

@neithernut is what @manuelmessner stated required? Does it add any improvement? I don't think so, as we have the issues and milestones, so there is absolutely no requirement for local todo tracking...

**Comment by neithernut** [comment]
I don't think we need a `.todo` either, but if users want it...

**Comment by matthiasbeyer** [comment]
You mean developers!?

**Comment by neithernut** [comment]
Er... yes.

**Comment by matthiasbeyer** [comment]
So,... should we add one? As stated, I consider this as useless! Would be nice to know why @manuelmessner wants this!

**Comment by TheNeikos** [comment]
I don't think it is needed _now_. However, everyone is free to edit their own .gitignore and just never check it in.

**Comment by matthiasbeyer** [comment]
So I'll merge this now?

**Comment by neithernut** [comment]
Yep.

**Comment by manuelmessner** [comment]
@matthiasbeyer:
The `.todo` file is part of my workflow. I use it as notepad for todos and random thoughts about a project.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
