### PR TITLE
Add calls to ws_hotkey_dag_deinit() in tests

### PR DESCRIPTION
**Pull request by matthiasbeyer**
(Was missing in #630)

This PR adds deinit calls in the dag tests, @xVin and me forgot to add those when writing the tests.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Unfortunately this fails because of dereferencing `0x107` or something! @neithernut I guess this is your department...

**Comment by neithernut** [comment]
I'll dive into it soon.

**Comment by neithernut** [comment]
I fixed the problem. Please integrate the patches into your branch and reorder them so the test shows up _after_ the fixes in the history.

**Comment by neithernut** [comment]
(semi-self) ACK.

---

I think in this case someone else beside @matthiasbeyer and me (e.g. @TheNeikos) should ACK this.

**Comment by TheNeikos** [comment]
That was a somewhat embarassing fix :P  

Ack codewise

**Pull request merged**
