### PR TITLE
Add ws_object_unlock() and make old unlock methods deprecated

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #118

### CODE REVIEW

**Comment by neithernut** [comment]
Add the deprecated attributes.
Also: we should ultimately remove them as soon as possible (definitely before v0.1)

**Comment by matthiasbeyer** [comment]
I cannot force people working on other branches to switch to the new interface, so the deprecated flag/attribute will be a notice and yes, should be fixed until v0.1 or something.

**Comment by matthiasbeyer** [comment]
Note: When merging other PRs which still use the old functions, the CI doesn't fail, but after the merge it failes. That's because the CI doesn't do a merge before building. So reviewing the other PRs should be done _really_ carefully!

**Comment by neithernut** [comment]
Or they should be rebased.

**Comment by neithernut** [comment]
Btw: ACK.

**Pull request merged**
