### PR TITLE
Add ws_socket deinit functionality

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #553

Something missing here? I'm not sure...

### CODE REVIEW

**Comment by TheNeikos** [comment]
Have you checked how to correctly stop libev in that case?

**Comment by matthiasbeyer** [comment]
Nope, that's one point I should do here, right? I don't know why, can you tell me?

**Comment by matthiasbeyer** [comment]
Please tell me whether the code in the latest commit is semantically correct.

**Comment by TheNeikos** [comment]
That is not correct, you will actually unloop the main loop, which will exit waysome.

**Comment by TheNeikos** [comment]
The correct one to use should be `ev_io_stop`

**Comment by matthiasbeyer** [comment]
I would need to pass a watcher to that function... But I do not have one...?

**Comment by TheNeikos** [comment]
The `io` member of the socket is a watcher

**Comment by matthiasbeyer** [comment]
uuuuuh...

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
Done. Into one commit. Hope you're fine with this?

**Comment by neithernut** [comment]
The loop is a singleton. It's unnecessary to store a reference in a socket, but I'm fine with this solution.

**Comment by matthiasbeyer** [comment]
Shall I remove the member?

**Comment by neithernut** [comment]
Yep.

**Comment by matthiasbeyer** [comment]
Where can I get the `loop` from to call `ev_io_stop()` with it then?

**Comment by neithernut** [comment]
The same way you get it initially: `ev_default_loop(EVFLAG_AUTO)`

**Comment by matthiasbeyer** [comment]
Updated (and already squashed).

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
