### PR TITLE
Cleanup deserializer code

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR includes style fixes, removes unneccessary variables,
scopes, checks and the like.

Pair-programmed with @manuelmessner

### CODE REVIEW

**Comment by manuelmessner** [comment]
ACK

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
Please suggest commits to squash.

**Comment by neithernut** [comment]
I browsed through the commits and found nothing to squash myself.
ACK.

**Pull request merged**
