### PR TITLE
Refactor: String callback helper added

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This patch adds a helper function in the string callback of the deserializer, to reduce code duplication

Targets #499.

### CODE REVIEW

**Comment by neithernut** [comment]
Format string should come first.

**Comment by matthiasbeyer** [comment]
You think so? It is just the format for the logging call...?

**Comment by neithernut** [comment]
Yep, but it's a wide-spread convention to have the format string first. I would rather _not_ violate it.

**Comment by matthiasbeyer** [comment]
Updated.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
