### PR TITLE
Fix iterations up the inheritance tree in objects

### PR DESCRIPTION
**Pull request by neithernut**
This fixes A bug I introduced into the code while fixing other stuff.

### CODE REVIEW

**Comment by neithernut** [comment]
Self ACK for the sake of progress.

**Comment by matthiasbeyer** [comment]
There was already a fix in one of my branches, whatthehell?

**Comment by matthiasbeyer** [comment]
And why the hell are you doing self-ACKs? This is not what our workflow is! Stop this!

**Comment by TheNeikos** [comment]
We needed it at that _moment_. I was beside him as he wrote it, so it was not a complete "self ACK"

**Comment by matthiasbeyer** [comment]
And here we have the point why I want the actual "ACK" in the issue.

**Pull request merged**
