### PR TITLE
Add syslog logging mechanism

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR changes the logging mechanism to use syslog(). The ability to
log to stderr is still available.

The interface for the already in use logging function calls is _not_
changed by this PR, but the implementation.

Review carefully.

### CODE REVIEW

**Comment by neithernut** [comment]
Please have a look at `wl_log`.

**Comment by matthiasbeyer** [comment]
Uuh... is this actually meant for the compositor?

Feel free to close this PR and open an issue for transforming for using `wl_log()`.

**Comment by neithernut** [comment]
It's offered through the `wayland-server.h` header. I will open a Pr soon.

**Comment by matthiasbeyer** [comment]
:+1:

**Pull request closed without merging**
