### PR TITLE
Add implementation for ws_value_set to string

### PR DESCRIPTION
**Pull request by matthiasbeyer**
My approach for `struct ws_value_set` to string via the `ws_value_union` type.

Related to #467.

### CODE REVIEW

**Comment by TheNeikos** [comment]
Can you test this before merging?

**Comment by matthiasbeyer** [comment]
Actually not, the deserializer is not able to deserialize sets by now.

**Comment by neithernut** [comment]
Would close unmerged, it will take a wile before this can actually _be_ implemented.

**Comment by matthiasbeyer** [comment]
Why exactly? This is just a to-string functionality...

**Comment by neithernut** [comment]
Then try to implement it without a relyable way to serialize _and_ deserialize `ws_object_id`s! That's clearly a prequisite for _this_ functionality. Hence, if we cannot have stringification of object ids yet, we also can't implement it for sets.

**Comment by matthiasbeyer** [comment]
Stringification of object ids is implemented in #588.

**Comment by neithernut** [comment]
If you're ok with implementing serialization without any concrete strategies for deserialization, ... Then I _guess_ it's ok to do it this way.

**Comment by matthiasbeyer** [comment]
The point of this is not serialization! The point of this is only logging, so there is no relation to de/serialization!

**Comment by neithernut** [comment]
If you don't intend to implement a more useful format, then I'll ACK this for squashing

**Comment by matthiasbeyer** [comment]
Depends. What do you think is a "more useful" format? I mean, with the `{ ... }` you immediately see that it is a set, with the adiitional `:N` you see how many elements are in there... I don't want to transform all elements to string! That would result in _way_ more overhead here, and as it is only for log()ing, I don't really see why we should need this complexity here...

**Comment by neithernut** [comment]
Then ACK for squashing.

**Comment by matthiasbeyer** [comment]
Done.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
