### PR TITLE
Cleanup user documentation format

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR tries to cleanup the user documentation format, so it looks nice.

Feel free to suggest things.

### CODE REVIEW

**Comment by neithernut** [comment]
I would have defered the formatting until 2015...
ACK for a4paper/12pt.

**Comment by neithernut** [comment]
The section numbering is odd btw.

**Comment by matthiasbeyer** [comment]
What do you mean with "odd"?

I'd not add more formatting stuff, as you said this should be done in january or so...

**Comment by neithernut** [comment]
Yep, but I can still add a note, so we remember it in January.
By odd, I mean that they always start with `0.`.

**Comment by matthiasbeyer** [comment]
That's indeed odd. If you want, I will investigate asap. But I guess it is not that urgent...

**Comment by neithernut** [comment]
It's not urgent.

**Pull request closed without merging**
