### PR TITLE
Add event deserialization

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR targets #375 (event deserialization).

Steps to do:
- [x] Event finalization -> compiling an `ws_event` from cached values
- [x] Recognition of "event" type
- [x] Support for event names
- [x] Support for event values, including
  - [x] Direct: nil
  - [x] Direct: bool
  - [x] Direct: int
  - [x] Direct: string
- [x] Tests

### CODE REVIEW

**Comment by neithernut** [comment]
Indirect values don't make sense for events.

**Comment by matthiasbeyer** [comment]
Fixed, tests are still missing.

**Comment by matthiasbeyer** [comment]
This is ready for review.

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
