### PR TITLE
Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by manuelmessner**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Looks good to me. Waiting for CI, of course.

**Comment by manuelmessner** [comment]
Done with:

``` bash
#! /bin/bash

files=()
for i in $(find . -type f -iname '*[c,h]'); do
    [[ $i =~ .git ]] && continue
    egrep -q '\s$' $i && files+=($i)
done

for i in ${files[@]}; do
    sed -i 's/\s*$//' $i
done

for i in $(git diff --name-only); do
    git add $i
    git commit -m "Remove trailing whitespace(s) in $i"
done
```

**Comment by neithernut** [comment]
Needs to be rebased.

**Comment by matthiasbeyer** [comment]
I added the WIP/on-hold label as this will be done after the buttload of PRs is merged, as some PRs _might_ introduce new trailing whitespace. ... you never know...

:smiley:

**Comment by manuelmessner** [comment]
Ok it's just a script call ^^
Just say when i shall execute it.

**Comment by matthiasbeyer** [comment]
I think we should do this ASAP. @manuelmessner wanna re-do this tomorrow in a session and get it merged asap?

**Comment by manuelmessner** [comment]
I'll do it in a few minutes

**Comment by manuelmessner** [comment]
Review pls.
I updated the script above for executions in future.
It generates the file list without interaction now.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
