### PR TITLE
Add test for ws_object

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Note for myself: The tests are not yet covered by the CI. After the PR is ready, add the appropriate CI configuration in this PR!

**Comment by matthiasbeyer** [comment]
@neithernut Please review f06a81e !

**Comment by neithernut** [comment]
The last commit is ok.

**Comment by TheNeikos** [comment]
Looks good to me as well

**Comment by matthiasbeyer** [comment]
@neithernut , @TheNeikos review pls.

**Comment by TheNeikos** [comment]
ACK for what I see

**Pull request merged**
