### PR TITLE
Fixes for the values/value.h header

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Blocks #97, #98, #99, #100

### CODE REVIEW

**Comment by neithernut** [comment]
ok.

**Comment by matthiasbeyer** [comment]
Does this mean ACK?

**Comment by neithernut** [comment]
Yep.

**Comment by matthiasbeyer** [comment]
I'm a god damn dumbass of a morron. This PR doesn't fix anything, it just moves code around. 

If you see this, you know I'm as stupid as hell.

**Comment by neithernut** [comment]
It looks cleaner now, though.

**Comment by matthiasbeyer** [comment]
It doesn't compile either. Fixup coming.

**Pull request merged**
