### PR TITLE
Add gitignore entries for Editors/IDEs and Emacs.

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Targets #60 and brings additional stuff.

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
@manuelmessner or @TheNeikos ?

**Comment by neithernut** [comment]
Solves issue #50.

**Comment by TheNeikos** [comment]
ACK from me as well

**Pull request merged**
