### PR TITLE
Remove unneccessary check from ws_connbuf_append

### PR DESCRIPTION
**Pull request by neithernut**
In some cases, you want to append 0 bytes to unblock the buffer.

### CODE REVIEW

**Comment by xVin** [comment]
ACK.

**Comment by TheNeikos** [comment]
Wouldn't it make sense to add an unblock method?

**Comment by neithernut** [comment]
Mh... maybe, but `ws_connbuf_append(foo, 0)` _must_ unblock the buffer.

**Comment by matthiasbeyer** [comment]
Sounds reasonable to me.

**Pull request merged**
