### PR TITLE
[WIP] Fix framebuffer creation

### PR DESCRIPTION
**Pull request by TheNeikos**
This fixes the encoder issue, and it selecting the wrong crtc.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
The commit message for e6b38ae is _way_ to short IMHO.

**Comment by matthiasbeyer** [comment]
The commit message for 0d9043e does not describe what you've done. There is code removed, which is not stated why (in the commit message).

I suggest you split the commit.

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
ACK.

**Pull request merged**
