### PR TITLE
Add event-transaction mapping in action manager

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is WIP, but I like to read suggestions. It adds support for
mapping transactions on events (by name) inside the action manager.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Targets #322 btw.

**Comment by neithernut** [comment]
I'll have a look at it later.

**Comment by neithernut** [comment]
This will not work, since `ws_set` will call `ws_object` methods on the struct, which, in turn, used the type information within the struct. This will cause the entire thing to happily segfault or worse (e.g. illegal instruction).
Wouldn't it make more sense to have the `ws_event` type, derive some type which has a list of transactions and use a comparision which is based on the event's name?

---

This may only work if `ws_object_cmp` allowes comparing two objects of which one's type is derived from the other's, so maybe we want to extend _that_ too.

**Comment by matthiasbeyer** [comment]
You did read my comment for the first member? `ws_set` will call `ws_object` methods, but it will automatically call these on the `ws_string` member, which is a `ws_object` itself.

Maybe I'm getting something wrong here, but the way it is it should work, as the `ws_string` member is embedded into the struct directly.

**Comment by neithernut** [comment]
Ah, now I get it. I didn't read carefully enough.

**Comment by matthiasbeyer** [comment]
:smiley:

**Comment by neithernut** [comment]
**Please** make the context a static anonymous struct like in **all** the other modules. Manually allocating this is completely bogous.

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
No need. 6 Commits is few enough, I guess. Feel free to suggest squashes, but I don't see need of any squashing here.

**Comment by neithernut** [comment]
I think the last two commits can be squashed.

**Comment by neithernut** [comment]
ACK.

**Comment by neithernut** [comment]
This was clearly merged too early. I'll have to rewrite parts of it.

**Pull request merged**
