### PR TITLE
Add ws_value_get_name()

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is a feature I would like to see merged for my work on #357.
It adds a function to get the name from a ws_value object.

Blocks #357

### CODE REVIEW

**Comment by neithernut** [comment]
Rename to `ws_value_type_get_name()` or something...

**Comment by matthiasbeyer** [comment]
Done. `ws_value_get_typename()`

**Comment by neithernut** [comment]
Name is unacceptable. The prefix is `ws_value_type`.

**Comment by matthiasbeyer** [comment]
Done.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
