### PR TITLE
Fix hotkey evaluation

### PR DESCRIPTION
**Pull request by neithernut**
This commit fixes a bug which causes the hotkey subsystem accept
successive key-presses instead of keeping keys pressed.

Target #532 and #534.

### CODE REVIEW

**Comment by neithernut** [comment]
I managed to correct the _wrong_ condition...
Please review now.

**Comment by neithernut** [comment]
Ahrg. Fuck it. I'll nitify you when it's ready.

**Comment by neithernut** [comment]
Mh... I found that even the hotkey never gets added with my testing config...
Maybe that's why I had a hard time spotting the bug...
(glaring at @matthiasbeyer)

---

So **now** I'm pissed. With the testing config you gave me, `ws_action_manager_process()` only get's called **once**, which a transaction which has **no flags set** (on the current `develop`). Obviously the DAG contains no nodes and no event will be emitted nor will any of the potentially problematic code in `ws_hotkeys_eval()` be triggered!
Are there **any** unmerged PRs you forgot to tell me about, @matthiasbeyer? Because obviously I can't reproduce a bug if the prequisites are not met!

I wasted a complete hour trying to reproduce it, given my low levels of concentration today!

**Comment by matthiasbeyer** [comment]
I'm sorry, but on the latest develop with the config I gave you, the `ws_action_manager_process()` function gets called twice for me, each time with a transaction which has at least one flag set.

I actually tried this on the latest develop with the configuration file I gave you:
- Start waysome with log level 8 in cgdb
- Put break point on `ws_action_manager_process()`
- Run
- Step to the point where the transaction flags are retreived
- Print these flags (register flag)
- Continue (which breaks at the `ws_action_manager_process()` function again)
- Step to the point where the transaction flags are retreived
- Print these flags (register flag and execute flag)

@TheNeikos and me debugged this yesterday and the dag was built up fine... as far as I can remember...

**Comment by neithernut** [comment]
When I check out current the `develop` branch, do a clean build, set a breakpoint at `ws_action_manager_process()` and run the whole thing, I see excactely **one** transaction.
Do you have **any** changes lying around which could have an influence on the result!?

**Comment by neithernut** [comment]
In the end, it was my fault.
I had a config lying around in my home directory, which was processed by waysome.
Since the deserializer didn't set **any** flags, I assumed the deserializer was broken. Hence the confusion.

I'm terribly sorry for yelling at people. Next time, I'll try to channel my frustration in another way.

**Comment by neithernut** [comment]
This finally works.

**Comment by matthiasbeyer** [comment]
I can execute my testing transaction with strg-alt-q if capslock is enabled, but I guess this is another issue.

I can not reproduce the bug, so this is a happy **ACK**!

**Comment by matthiasbeyer** [comment]
For the record: Capslock is not a problem here, as we watch out for the key codes, not the actual "letter" or something.

**Pull request merged**
