### PR TITLE
Structure the main function

### PR DESCRIPTION
**Pull request by neithernut**
This PR designates areas of the main function for initialisation, the main loop and the deinitialisation.
Targets issue #44. (by introducing another approach).

### CODE REVIEW

**Comment by neithernut** [comment]
To have no unused label dangling around, I'd like to merge #48 if it's done and rebase this afterwards.
This is not the order which the issues suggest, but it's cleaner.

**Comment by matthiasbeyer** [comment]
Does not build.

I wouldn't merge this.

**Comment by neithernut** [comment]
That was intended. I will rebase as soon as I'm done with my current work.

**Comment by neithernut** [comment]
I'm done now.

**Comment by matthiasbeyer** [comment]
ACK.

**Pull request merged**
