### PR TITLE
Add content to "files" section of user documentation

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #444

Please review.

### CODE REVIEW

**Comment by neithernut** [comment]
Mh... maybe we should use inline listings for the files, but I'm not quite sure how this interacts with `latex2man`...

**Comment by matthiasbeyer** [comment]
What do you mean by "inline listings"? Putting source code in the (user-)documentation?

**Comment by neithernut** [comment]
I mean using `lstinline` for paths, which e.g. causes usage of another font and _maybe_ also colours env-vars used in the path.

**Comment by matthiasbeyer** [comment]
Just discovered that there is `\path` around.

**Comment by matthiasbeyer** [comment]
`\path` does not variables. I opened a question on texoverflow how to do it inside a `\path{}`, but I don't think it is possible. If it is not possible, I will write a command which results in a simple `bash`-listing environment.

I'm now setting this on hold until I get a sufficient answer on texoverflow, but I will not wait that long.

**Comment by neithernut** [comment]
`latex2man` actually sets a "variable" with which one can check whether a manpage is created or not. Using this, we can create a command which does "the right thing" for both manpages and PDFs.

**Comment by matthiasbeyer** [comment]
Can you tell me how to build the man page? My `.1` file only contains the note that it is generated, but no content by now... maybe I've gotten something wrong,... don't know.

**Comment by neithernut** [comment]
I think the manpage.tex is missing some elements. See http://ctan.space-pro.be/tex-archive/support/latex2man/latex2man.html. (maybe open an issue for that)

---

I'll open an issue.

**Comment by matthiasbeyer** [comment]
`latex2man` actually does not understand `\input`. I suggest dropping it, as it is not of any benefit for us anymore.

**Comment by neithernut** [comment]
So, you suggest _not_ to have a man-page?

**Comment by matthiasbeyer** [comment]
Nope. I suggest to dropping `latex2man`.

**Comment by neithernut** [comment]
So you want to hand-craft a manpage?

**Comment by matthiasbeyer** [comment]
Not really.

My point is that using latex2man gives us no benefit over writing it by hand, except for writing it in latex. So, the initial point of writing parts of the documentation once and have them both in the pdf and the manpage just vanished.

Although I see no alternatives between latex2man and writing one by hand.

---

What I'd like to suggest: Put the whole manpage stuff on the back burner. We can write a manpage when we are in v1.0, but it is really not worth the effort right now.

**Comment by neithernut** [comment]
k, so you'll write one by hand. (btw: I did this once)

**Comment by matthiasbeyer** [comment]
I guess this shouldn't be discussed here anyways, as this PR targets on another topic. So,... what about the patch now?

**Comment by neithernut** [comment]
Was marked as WIP and on hold, so I didn't bother reviewing it.
Now that I did: ACK.

**Pull request merged**
