### PR TITLE
Add status badges for branches in README.md

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #592

### CODE REVIEW

**Comment by TheNeikos** [comment]
ACK

**Comment by neithernut** [comment]
Keep in mind that that README will also be shipped.

**Comment by matthiasbeyer** [comment]
What do you mean with "shipped" in this context?

**Comment by neithernut** [comment]
As in "shipped as part of a source package" (e.g. a zip file).
Btw: this approach also doesn't show the state of the actual version you're viewing but the current version.

**Comment by matthiasbeyer** [comment]
Yes, I am (we are) aware of that.

I don't understand what you mean with your "Btw:...".

**Comment by neithernut** [comment]
If, at any point of time in the future, you browse through the history and get the readme displayed, the badges still indicate the _current_ state and not the state the repository was in when the commit you're viewing was committed or authored.
And even if github is smart enough to do "the right thing" here, other plattforms, which might be used to view the repository (in the future), will not handle this correctly.

**Comment by TheNeikos** [comment]
Tbh that is a non issue, whatever the 'badges' show is not important. It's meant to show how healthy a project is and if it the lastest stage actually builds. It's basically a contract from us to others to make sure that there is always a buildable state.

Now, previous versions do not interest us that much right now. We're not a company with long lasting stable releases and shouldn't need them. Hence why it's not really important that the badges show future versions because they are the only things that matter!

**Comment by neithernut** [comment]
Of course, only future releases matter. But from the point of view of a future self, the current release is a previous one. My point is that you break the concept of "I'm viewing an old release, so _all_ the content I see is from back then." by introducing badges this way.

**Pull request closed without merging**
