### PR TITLE
[WIP] Added Framebuffer creation

### PR DESCRIPTION
**Pull request by TheNeikos**
This is for #43

### CODE REVIEW

**Comment by neithernut** [comment]
You could add the debugging output calls.

**Comment by neithernut** [comment]
Did you manage to solve the issues which were still there when I left? (distorted image)

**Comment by TheNeikos** [comment]
Yes I did, the duck showed nicely and in correct colors.

**Comment by neithernut** [comment]
ACK.

**Comment by TheNeikos** [comment]
Don't merge yet, I still want to add a few things.

**Comment by neithernut** [comment]
If the changes are small that would be ok, but if the changes are huge, please postpone them or do them in another PR, because:
- The milestone is due today
- I'll not close this milestone untill the issues associated with is are resolved
- The issues are not resolved before this is merged

Note: I'm not gonna brag about it if we miss this one milestone by a day, so no pressure.

**Comment by TheNeikos** [comment]
Yes, it can be merged then, I will put the code somewhere else I modified.

**Pull request merged**
