### PR TITLE
Setup for developer documentation

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR starts the setup for the developer documentation.

Targets #552.

### CODE REVIEW

**Comment by neithernut** [comment]
I especially like that you dropped `doc/custom` for `doc/developer` makes things easier to understand for people browsing the tree.

**Comment by matthiasbeyer** [comment]
I did not "drop" it, but created another directory. We still need the `doc/custom` directory later on, for the main page for example.

But yes, I thought this would be a bit better structure then putting everything in `custom`.

**Comment by neithernut** [comment]
Wouldn't it make sense to integrate those into `developer`, too?

---

Mh.. we now have the sectio "waysome" and the sectio "Modules" the first one should be integrated into the latter, imho (at least the module main pages and the MD files which are integrated in the source tree).

**Comment by matthiasbeyer** [comment]
I played around a bit and I guess that would be hard to do... I'm not sure how to do it... so feel free to play around with it and provide patches for this PR, but don't get frustrated!

**Comment by neithernut** [comment]
Working on this, I get the serious feeling that either doxygen or our grouping is seriously broken. Check out the commit on my branch. I _just_ added the MD file to the object group, but suddenly a bastard definition of `ws_object` and `ws_string` turns up in the _logger_. WTF? I get that adding MD files to groups _may_ not be supported (for whatever reason), but instead of simply ignorign the `@addgroup`, doxygen fuck's up the document struture!

---

Suddenly I feel the urge to come up with a better piece of software for documenting, but neither do I have the time nor is it a good idea to postpone this until I would have completed that.
Anyways, regarding personal usage, I'll declare doxygen a member of the "broken piece of shit"-group, where it shares a special place with other Qt-related software.

**Comment by matthiasbeyer** [comment]
... didn't I tell you to _not_ get frustrated? It's definitely not doxygens but our own fault here, I just weren't able to catch it by now...

Doxygen is an awesome tool, we're just not able to use it in the right way by now!

---

I will check out your stuff now...

**Comment by matthiasbeyer** [comment]
After some investigation I found out how to do it. I will provide patches as soon as I wrote them...

**Comment by matthiasbeyer** [comment]
The pages are now subpages of the appropriate documentation module. Anyways, they still get included as top-level pages, which I don't think is what we want. I will try to remove them as top-level pages another time...

**Comment by neithernut** [comment]
Being the only tool usable at all doesn't make it "great".
If you can fuck up the document structure by that extend by _simply_ adding _one_ file to a group/section, the system is busted.

**Comment by matthiasbeyer** [comment]
Calm the **FUCK** down. You just used the wrong command, that's it!

**Comment by neithernut** [comment]
I _am_ cal. I'm just done with tools that try to do more than they should, in a way which constrains the usecases they might be used for, and in a bad way on top of that.
Doxygen is a prime example for such a tool.

Btw: I think I need a hint from you in what way the document structure was enhanced. I don't see any enhancements.

**Comment by matthiasbeyer** [comment]
I'm ready for review now.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
