### PR TITLE
Fix: Add space after debug prefix for object type

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by neithernut** [comment]
We could also adjust the log message creation so it adds the whitespace and the brackets.

**Comment by matthiasbeyer** [comment]
But I would introduce another feature for that, something like a member `tag`. So you set `tag` to `"Object"` and it creates `"[Object] "` out of it. And the tag should then go _before_ the actual prefix.

**Comment by neithernut** [comment]
That doesn't sound sane.

**Comment by matthiasbeyer** [comment]
Why not, that's what you suggested. A prefix is not the same as a `"[something]"` tag.

**Comment by neithernut** [comment]
Having a prefix _and_ a tag sounds nonsensical.

**Comment by matthiasbeyer** [comment]
I consider a tag as some meta-information, where a log is located (Hey, I'm from the connector implementation) and a prefix for in what context it happened (Hey, I'm logging here while receiving stuff).

Another idea would be, to have a list of tags which gets prepended to the actual log. But that results in a way more complex algorithm that way, and as we may replace the whole logging stuff at some point (maybe) it sounds like unrequired effort for me.

**Comment by matthiasbeyer** [comment]
I guess the discussion should be held in an appropriate issue, not here. Can you please review and ack?

**Comment by matthiasbeyer** [comment]
Can we please get this merged or not?

**Comment by neithernut** [comment]
ACK, albeit the underlying issue stays unresolved.

**Pull request merged**
