### PR TITLE
Add method for setting background

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR adds support for setting background via the API.

Targets #438

### CODE REVIEW

**Comment by neithernut** [comment]
Will probably be moved into the egl renderer or something...

**Comment by matthiasbeyer** [comment]
Could this codebase be reused maybe? So can we merge it?

**Comment by neithernut** [comment]
I'm not _quite_ sure whether this should go into the monitor or the egl rendering target... (subspaces with custom backgrounds!!!!11!!eleven)

**Comment by matthiasbeyer** [comment]
I just re-checked the code in this PR. It works with the `ws_monitor` interface, so if the egl stuff implements the interface, this should all work.

We might refactoring this PR, though, because we can set object attributes now way more elegant (the code for the actual command _could_ be emitted)...

**Comment by neithernut** [comment]
Setting an attribute is not sufficient, since you actually have to _do_ something to load the image.
Nevertheless, `ws_buffer_blit` will vanish, so you'll have to rewrite the command (preferably by loading the image into a texture).

**Comment by matthiasbeyer** [comment]
So, I think I will wait until the infrastructure for this is up.

**Comment by neithernut** [comment]
That's excactly what I told you back when I set this "on hold" in the first place.

**Pull request closed without merging**
