### PR TITLE
Convert JSON doc from markdown to tex

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #327

### CODE REVIEW

**Comment by neithernut** [comment]
You may now procees adding this to the user documentation.

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
Done. Actually, just one commit made sense to be merged into other commits (The "fix listing notation" one).

Hope you're fine with this.

**Comment by neithernut** [comment]
Yep.

**Pull request merged**
