### PR TITLE
Make the CI perform a merge before building

### PR DESCRIPTION
**Pull request by neithernut**
This (hopefully) prevents us from fucking up the upstream branches.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Can you please tell me what you're doing here? What is the variable for, what holds it and who sets it?

**Comment by neithernut** [comment]
Drone sets it.
Still testing btw.

**Comment by matthiasbeyer** [comment]
And what does it hold?

**Comment by neithernut** [comment]
The branch in which the PR is merged (it it's a PR)

**Comment by matthiasbeyer** [comment]
[Maybe relevant](http://stackoverflow.com/questions/3161204/find-the-parent-branch-of-a-branch) (See second answer)

**Comment by matthiasbeyer** [comment]
Seems you need to set user information. This data could be set to dummies.

**Comment by neithernut** [comment]
Insufficient. A baranhc may also be based on a WIP form another repo. In this case it would even be unclear whether the branch is to be merged to the coworker's branch or develop.

**Comment by matthiasbeyer** [comment]
Branches should only be merged into the branch they start from, that's one of our guidelines, if you remember!

**Comment by neithernut** [comment]
You forget a whole lot of things here. E.g.: What about release-preparing branches? They are _based_ on the develop branch, but they are merged onto the _master_!

**Comment by matthiasbeyer** [comment]
That's true. :disappointed:

**Comment by matthiasbeyer** [comment]
So, you have to set the git user data. Try something like `@USER@$HOSTNAME` or something,... or "nobody@nohost"...

**Comment by neithernut** [comment]
Already done. We were discussing whether we should set it globally on the server, but @TheNeikos favored setting it in the `drone.yml`.

**Comment by matthiasbeyer** [comment]
Hm. Looks good so far. I prefer this setup, too. I guess everything has to be rebased after this gets merged, right? I guess it is not that critical to rebase everything, but yeah, it should be rebased.

As this happens inside a VM, nothing gets affected here... I love drone! :-)

happily: ACK!

**Pull request merged**
