### PR TITLE
Fix image data

### PR DESCRIPTION
**Pull request by TheNeikos**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
ACK.

I feel ashamed btw. I thought I had removed the buffer member from the raw buffer type... but it seems I didn't. Please do not _only_ blame me, but also the reviewer(s). :smile:

**Comment by neithernut** [comment]
ACK.

**Comment by TheNeikos** [comment]
:tongue: Nobody is really blaming you, it doesn't matter tbh. It's always fun though to find out how errors happen :)

**Comment by matthiasbeyer** [comment]
@TheNeikos :kiss:

**Pull request merged**
