### PR TITLE
Update JSON API documentation

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Updates include:

```
* We use constants as arguments in a overhead free way now, so
  integers are really integers and if one wants to specify stack
  positions, a special json object has to be used.

* Removal of documentation sections saying something else.

* Note that doubles are not yet supported.
```

---

The above is also in the commit message (as this is a one-commit PR).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Blocks #260

**Comment by matthiasbeyer** [comment]
:anguished:

**Comment by neithernut** [comment]
ACK.
Please update the state charts as well. May be done in a different PR.

**Comment by matthiasbeyer** [comment]
Done.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
