### PR TITLE
Add support for WS_VALUE_TYPE_NAMED in ws_value_union_init_from_val()

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #467 (`src/values/union.c`) partially.

### CODE REVIEW

**Comment by manuelmessner** [comment]
ACK

**Comment by neithernut** [comment]
What about `object_id` and `set` values? You circumvent refcounting for them.

**Comment by matthiasbeyer** [comment]
Sorry, but I don't get your latest comment.

**Comment by neithernut** [comment]
Sorry, I was rather confusing.
Copying the pointer means you end up with two references to the same value. Now what happens when one of the value gets deinitialized?
I'd rather pleadge for using a value union in named value type and using `ws_value_union_init_from_val()` recursively here.

**Comment by neithernut** [comment]
This is still not acceptable. I suggest rewriting `ws_value_named` here, to hold a value unioon instead of a pointer to a value.

**Comment by matthiasbeyer** [comment]
Pushed for backup, not for review.

**Comment by matthiasbeyer** [comment]
I guess this can be reviewed now...

**Comment by neithernut** [comment]
If we do #511, we can also close this unmerged.

**Comment by matthiasbeyer** [comment]
Of course.

**Pull request closed without merging**
