### PR TITLE
Add width/height setter methods for ws_shell_surface

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #457.

I'm not sure about the convenience method, which allows setting of the
width and height in one step, but I think it is basically a good idea.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@TheNeikos please review here!

**Comment by neithernut** [comment]
Given the wayland interface, it makes more sense updating width and height at the same time.
Please have a look at `wl_surface`, `wl_shell_surface` and the like. E.g. `wl_shell_surface_send_configure()` is of interest.

**Comment by matthiasbeyer** [comment]
Hm. I think it's suiteable to provide some convenience here and export setters for width and height only as well... don't you think so?
@TheNeikos what about you?

**Comment by neithernut** [comment]
All the methods need to be relocated into either `ws_abstract_shell_surface` or `ws_surface`.

**Comment by matthiasbeyer** [comment]
I'd like to wait for #539 , so I can avoid heavy rebasing here.

**Comment by matthiasbeyer** [comment]
I did a complete rewrite of the branch. Please review.

**Comment by neithernut** [comment]
ACK so far, but could you try to implement the `todo`s you added in this PR? (e.g. using the set-width-and-height-method for setting width and height, setting the other value to the current one).

**Comment by matthiasbeyer** [comment]
Of course I will do this!

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
done.

**Pull request merged**
