### PR TITLE
Add call for help in README.md file

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Hi guys.

I'd like to add this to the `README.md` as it seems we are stuck on this problem.

What do you think?

@xVin @manuelmessner @neithernut @TheNeikos

### CODE REVIEW

**Comment by TheNeikos** [comment]
I believe to have found the issue, will make a pr once I am back in Furtwangen :)

**Comment by matthiasbeyer** [comment]
Sounds nice, but... you know we debugged and debugged and weren't able to find the issue... so I'm looking forward to it, but I'm sceptical...

**Comment by TheNeikos** [comment]
I find your lack of faith... disturbing.

**Comment by matthiasbeyer** [comment]
It is not a lack of faith! I'm just realistic! :smile:

**Comment by matthiasbeyer** [comment]
@TheNeikos So where is your PR?

**Comment by TheNeikos** [comment]
It is in the OpenGL PR of course since that's where we are stuck?

**Pull request closed without merging**
