### PR TITLE
Change test build setup to allow one test per object type

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This changes the build setup for the tests, so we can have one test
file per object type, which was not possible before:

```
tests/check/objects/ws_object/test.c - for ws_object type
tests/check/objects/ws_set/test.c - for ws_set type
tests/check/objects/ws_array/test.c - for ws_array type
```

And so on.

The appropriate cmake files for the single tests have to be added by
the author of the related test source file. Also, the entry for the
subdirs for everything else then "ws_object" have to be added by the
test authors.

---

This setup should also allow a several-file test for one type.

---

@neithernut, @TheNeikos please review carefully, you guys know that
I'm not so good with cmake.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Blocks #180, #181, #182

**Comment by neithernut** [comment]
Should work, go on.

**Comment by matthiasbeyer** [comment]
@TheNeikos can you review, too, please?

**Comment by TheNeikos** [comment]
Looks goo to me.

**Pull request merged**
