### PR TITLE
Add support for custom error strings in ws_errno_tostr()

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Feel free to suggest more changes.

### CODE REVIEW

**Comment by neithernut** [comment]
This is _nasty_.

**Comment by matthiasbeyer** [comment]
Why?

---

I'd happily change the behaviour if you tell me how to find out what errno number is the highest...

**Comment by neithernut** [comment]
I doubt that custom errnos are of _any_ use here at all. Extending the errnos in an executable is a _bad_ idea. Using the logging facility directly is preferable.
If you want extensible error reporting from functions' return codes, use a language which supports exceptions.

**Comment by matthiasbeyer** [comment]
And if you want to return errors to the plugin?

**Comment by neithernut** [comment]
Returning error codes which are an _expansion_ or errnos is even worse.
You set an invalid error code (e.g. `0`) in the error reply and attach the error string as you usually would.

**Comment by matthiasbeyer** [comment]
So how do we then provide a unique way to find error explanations? Meaning a single instance where the error strings are hardcoded, so we do not have code duplication...

**Comment by neithernut** [comment]
With another system which does **not** interfere with `errno`! E.g. a second function which delivers error strings/formats for enums.
But given an error case which can _not_ be described using a standart-errno-string, the probabilty to have this twice is quite low, so the amount of duplicated code is _minimal_. Hence, I'd close this unmerged.

**Comment by matthiasbeyer** [comment]
ACK for closing this unmerged.

**Pull request closed without merging**
