### PR TITLE
Cleanup serializer

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Cleanup serializer code.

Pair programmed with @manuelmessner

### CODE REVIEW

**Comment by manuelmessner** [comment]
ACK

**Comment by neithernut** [comment]
ACK for squashing.

**Comment by matthiasbeyer** [comment]
Please suggest commits to squash.

**Comment by neithernut** [comment]
Just browsed the commits and it seems there is nothing to squash atm, but I found something nasty/strange.

**Comment by matthiasbeyer** [comment]
~~Do you want to tell me?~~

---

Edit: Sorry, didn't see the commit annotation in the first place.

**Comment by matthiasbeyer** [comment]
Can be merged IMHO.

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
